# https://gecgithub01.walmart.com/mobile-platform/github-app-monolith
enabled_features:
  - autolabeler
  - bot-pr-merge
  - semantic-pull-requests
  - stalebot
  - merge-queue
  - pr-template-validator
  - stale-branch-bot
  - sync-base-branch
  - bot-admin-merge
  - bot-translation-merge
merge_user: SVC_walmart_web_bot
add_pr_label: allowRetry
sync_base_branch_on_changed_files_intersect:
  - "^libs\/.*\/src\/"
  - "^apps\/.*\/app\/"